<section id="footer">
        <footer>
            <nav>
                <ul>
                     <li><a href="index.php">Home</a></li>
                    <li><a href="fav_form.php">Survey</a></li>
                    <li><a href="friends.php">Meet the Crew</a></li>
                    <li><a href="about.php">About Doki</a></li>
                    <li><a href="contact.php">Contact</a></li>
                </ul>
            </nav>
            <p>© 2025 Swinburne University of Technology - All Fun and No Stress</p>
        </footer>
    </section>