<section id="header">
        <header>
            <img id="logo" src="images/doki_logo.png" alt="A cat who sells ice cream"> 
            <h2>Little Doctor: Doki the Cat</h2>
        </header>
        <nav>
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="fav_form.php">Survey</a></li>
                <li><a href="friends.php">Meet the Crew</a></li>
                <li><a href="about.php">About Doki</a></li>
                <li><a href="contact.php">Contact</a></li>
                <li><a href="login.php">Login</a></li>
            </ul>
        </nav>
    </section>